slam_toolbox:
  ros__parameters:
    use_sim_time: true
    solver_plugin: solver_plugins::CeresSolver
    map_file_name: /tmp/lab_map
    mode: mapping
    map_update_interval: 5.0
    max_laser_range: 10.0
    minimum_travel_distance: 0.3
    minimum_travel_heading: 0.3
